### ISSUE TITLE
Correct broken links to ethics supplements

### ISSUE THREAD

**Issue by drpaulralph** [acmsigsoft/EmpiricalStandards#10]
Correct broken links to ethics supplements

**Comment by Taher-Ghaleb** [comment]
Oh, I was assuming Arham would add them to markdown.

**Comment by Taher-Ghaleb** [comment]
Also, I see some supplements don't exist yet (e.g., Replications Supplement and Multimethodology Supplement)

**Comment by drpaulralph** [comment]
1) I don't know what you mean by "add them to markdown" -> the script that finds links seems to break unless the link begins with "see the..." id I miss something? Feel free to follow up on teams. 

2) Replications doesn't exist yet so we should comment out those references. The Multimethodology supplement does exist but has been renamed to the Multimethodology and Mixed Methods standard.

**Comment by Taher-Ghaleb** [comment]
I have already fixed that. Now it doesn't look for "_see_" or "_see the_" anymore. It looks for links now. Oh, maybe you are looking at the master branch and didn't merge my changes yet.

**Comment by Taher-Ghaleb** [comment]
Fixed by [ab87bb7](https://github.com/acmsigsoft/EmpiricalStandards/commit/ab87bb7).

**Comment by drpaulralph** [comment]
Still not working. Check performance on https://web.cs.dal.ca/SIGSOFT-Empirical-Standards before closing.

**Comment by drpaulralph** [comment]
now it's fixed!

**Comment by Taher-Ghaleb** [comment]
I checked and it works fine over there. What's not working exactly?

**Comment by Taher-Ghaleb** [comment]
Great.
