### ISSUE TITLE
Rearrange list of standards

### ISSUE THREAD

**Issue by drpaulralph** [acmsigsoft/EmpiricalStandards#110]
On [this page](https://www2.sigsoft.org/EmpiricalStandards/docs/), instead of a bunch of square buttons, make a list of standards organized as follows. **Note the starred items.** Note also some minor renaming (e.g. Experiments to Experiment) that can be done along with this change as long as it doesn't break the checklist generator.

### General
General Standard
Engineering Research
Mixed Methods

### Qualitative
Action Research
Case Study
Grounded Theory
Qualitative Survey

### Quantitative
Benchmarking
Data Science
Experiment
Longitudinal
Optimization Study
Quantitative Simulation
Questionnaire Survey
Repository Mining

### Literature Review
Case Survey
Critical Review*
Meta Analysis*
Meta Synthesis*
Systematic Review* 

### Other
Meta Science
Replication

*We're in the process of dividing the Systematic Review Standard into Critical Review, Meta Analysis and Meta Synthesis. Work with what's there.

**Comment by eschltz** [comment]
Should this be formatted as a side menu or kept at the top of the page?

**Comment by drpaulralph** [comment]
I think it should be at the top of the page, but written like a table of contents instead of a bunch of boxes.

**Comment by eschltz** [comment]
@drpaulralph Done in the PR above. You can check a live example at https://eschltz.github.io/standardstest/docs/
