### ISSUE TITLE
Accept-message

### ISSUE THREAD

**Issue by drpaulralph** [acmsigsoft/EmpiricalStandards#12]
As a reviewer, 
if I select "yes" to all essential criteria"
I get a message in red at the end of the essential criteria but before the desirable criteria that says "The manuscript meets all essential criteria and should be accepted."
So that I know what decision I should enter.

**Comment by arhamarshad1** [comment]
Any update?

**Comment by drpaulralph** [comment]
Clarification: the accept message should display if the user clicks yes to all the essential criteria OR if, for all deviations, they indicate that the deviation is reasonable.

**Comment by Taher-Ghaleb** [comment]
I see. I fixed the issue, but now will add the other condition "OR if, for all deviations, they indicate that the deviation is reasonable."

**Comment by drpaulralph** [comment]
Great job guys.
