### ISSUE TITLE
Delete the "does the manuscript justify the deviation?" follow-up question

### ISSUE THREAD

**Issue by drpaulralph** [acmsigsoft/EmpiricalStandards#15]
Replace with:
Is the deviation reasonable?
Yes: "OK. Not grounds for rejection"
No: "Explain in your review why the deviation is unreasonable and suggest possible fixes. Reject the paper unless fixes are trivial. 

Tooltip on "is the deviation reasonable": If the manuscript justifies the deviation, consider the justification offered.

**Comment by drpaulralph** [comment]
Still not working.

**Comment by arhamarshad1** [comment]
Updating server (wasn't updated that's why you couldn't see changes)

**Comment by drpaulralph** [comment]
Fixed!
