### ISSUE TITLE
Issue to track topics that are not yet, yet might be, covered

### ISSUE THREAD

**Issue by davisjam** [acmsigsoft/EmpiricalStandards#2]
...in case this is useful. (Close if not)

So far I see:

- Focus groups
- Mixed-methods

**Comment by drpaulralph** [comment]
A list of planned standards follows. Some of these are in development. Others need volunteers. Feel free to suggest further standards. Please let me know if you would like to contribute to drafting any of the planned or suggested standards.  

Case Survey
Discourse Analysis (e.g. studying StackOverflow)
Ethics Supplement
Ethnography and Phenomenology
Exploratory Data Science (Repository Mining)
Longitudinal studies including Panel & Cohort studies
Multi-methodology / mixed-methods
Protocol analysis
Replication studies
Simulations

**Comment by mcoblenz** [comment]
Usability studies, which focus on low-cost identification of key usability problems in the design of artifacts.

**Comment by drpaulralph** [comment]
We've made a bunch of the missing standards. Updated list of potential standards as follows. 

- Focus groups
- Discourse Analysis (e.g. studying StackOverflow)
- Cohort studies
- Repository mining that isn't a longitudinal study or data science (I still don't know what to do about such studies)
- Qualitative simulations and protocol studies
- Replications supplement
- Usability studies?

**Comment by drpaulralph** [comment]
I'm closing this issue and moving the content into "Discussions" (see the discussions tab).
