### ISSUE TITLE
typically have a predictive/preemptive/corrective modelling?

### ISSUE THREAD

**Issue by timm** [acmsigsoft/EmpiricalStandards#24]
@drpaulralph  writes

I get what you're saying about "data-scientific endeavours typically have a predictive/preemptive/corrective modelling in mind by design" Should we state this in the application section? I.e., "applies to studies that primarily analyze existing software engineering artifacts," ... "using predictive, preemptive or corrective modelling"? Does that make sense? 

but I don't see that in current text https://github.com/acmsigsoft/EmpiricalStandards/blob/master/docs/DataScience.md.

is this still current?

**Comment by timm** [comment]
this one also seems non current

Can you make this more concise? "discusses threats to validity identifying construct validity and limitations or technical assumptions (using an appropriate framework either using common standards<sup>[2](#myfootnote2)</sup> or a threat to validity appropriate to this study)." You don't have to say "discusses threats to validity / construct validity" because that's already in the general standard.

**Comment by timm** [comment]
ditto. still current?

""for studies not based on proprietary data: a replication package is made available that conforms to SIGSOFT standards for a functional artifact. and if data cannot be shared (e.g. an industrial case study), it is desirable to create a sample dataset that can be shared to illustrate the use of the algorithms." Can we write this in a way that doesn't assume the reader knows what's in the SIGSOFT standards for a functional artifact? Can we separate the issue of having a replication package with a bunch of stuff in it from the issue of that replication package including actual data vs sample data? "

**Comment by drpaulralph** [comment]
@timm, Damian and I went through the standard together and fixed most of the issues.  I added a line to the application section - please check and close issue if acceptable. More suggestions are welcome.

**Comment by timm** [comment]
very good
