### ISSUE TITLE
Give each standard its own URL

### ISSUE THREAD

**Issue by drpaulralph** [acmsigsoft/EmpiricalStandards#28]
As someone interested in a specific standard,
I want to give someone a url to that standard, such as https://acmsigsoft.github.io/EmpiricalStandards/standards/experiment, 
so that they can view that standard directly without having to go to https://acmsigsoft.github.io/EmpiricalStandards/docs/ and choose from a list.

**Comment by Taher-Ghaleb** [comment]
Does it necessarily need to be separate pages (e.g., "docs/CaseStudy")?

It is simpler to make it as a parameter assigned to the same page (e.g., "docs?standard=CaseStudy").

**Comment by drpaulralph** [comment]
Either would be fine. docs/CaseStudy would be marginally better from a usability perspective, but if docs?standard=CaseStudy is significantly easier to implement, it's ok.

**Comment by Taher-Ghaleb** [comment]
Right. I suggested doing it like "docs?standard=CaseStudy" to keep all on the same page. Doing it like "docs/CaseStudy" would require creating additional separate pages for each standard in which we markdownify the contents.

**Comment by Taher-Ghaleb** [comment]
I've implemented it like "docs?standard=CaseStudy". Please check it out. Thanks.

**Comment by Taher-Ghaleb** [comment]
I've implemented it like "docs?standard=CaseStudy". Please check it out. Thanks.

**Comment by drpaulralph** [comment]
Looks good to me.
