### ISSUE TITLE
github.io links -> github.io pages

### ISSUE THREAD

**Issue by drpaulralph** [acmsigsoft/EmpiricalStandards#29]
As an author or reviewer using the checklist generator, 
When I click on the name of a method, I want to go to the page for the corresponding standard on the github.io site instead of going to the corresponding standard in on the github.com repo. 

Before attempting this issue, please resolve issue 28: https://github.com/acmsigsoft/EmpiricalStandards/issues/28

**Comment by drpaulralph** [comment]
All of the relative links in the checklists (e.g. describes in detail what, where, when and how data were collected (see the Sampling Supplement) should also point to the pages on gtihub.io rather than the markdown files in the repo.

**Comment by Taher-Ghaleb** [comment]
> As an author or reviewer using the checklist generator,
> When I click on the name of a method, I want to go to the page for the corresponding standard on the github.io site instead of going to the corresponding standard in on the github.com repo.

This should be done easily.

<br>

> All of the relative links in the checklists (e.g. describes in detail what, where, when and how data were collected (see the Sampling Supplement) should also point to the pages on gtihub.io rather than the markdown files in the repo.

So, you mean when someone accesses the standards/supplements from the repo, links should point to markdown files in the repo, but while using the checklist generator, links should point to gtihub.io instead?

**Comment by drpaulralph** [comment]
Yes - if you're on github.io, the links should point to other html pages on github.io. If you're looking at a standard on the repo, the links should point to other markdown files on the repo.

**Comment by Taher-Ghaleb** [comment]
I think this issue is now fixed everywhere. We can reopen if something is still missing.
