### ISSUE TITLE
Add "too few participants" as an invalid criticism to experiments with human participants

### ISSUE THREAD

**Issue by mcoblenz** [acmsigsoft/EmpiricalStandards#3]
In the “Experiments (with Human Participants)” section, I suggest adding as an invalid criticism “too few participants unless there is an objection to the statistical analysis or participant selection process.” Too often, I see reviewers eyeballing the number of participants in studies and complaining that it doesn’t look like enough participants. Presumably the reviewers are trying to address external validity, but the way to address that is either via objections to the statistical analysis or results, or objections to the participant pool or selection process.

**Comment by CaptainEmerson** [comment]
plus one

**Comment by turhanb** [comment]
This can be a valid criticism, though, particularly when the experiment yields a negative result. Author’s inclusion of the desirable attribute “presents a-priori power analysis and sufficient n for expected effect sizes” would preempt such eyeballing criticism.

**Comment by mcoblenz** [comment]
Well, if the experiment has a negative result, then either there was insufficient power, or the result is interesting and should be considered for publication (depending on other factors, of course). So the objection the reviewer should write in that case is not "too few participants" but "insufficient power." It could be that the power analysis was flawed due to an underestimate of variance, but that's about variance, not sample size.

**Comment by drpaulralph** [comment]
I've threaded this needle by adding antipattern "not enough participants (unless supported by power analysis)."
