### ISSUE TITLE
Move recommended decision to top of txt export

### ISSUE THREAD

**Issue by drpaulralph** [acmsigsoft/EmpiricalStandards#31]
Currently the decision is underneath the lists. Move it to the top, as shown below. Do this for both one-phase and two-phase checklists.

=================
Review Checklist
=================

Recommended Decision: REJECT. [or ACCEPT, or REVISION, etc.]

In your review please explain the deviations and why they are not reasonable. Give constructive suggestions. [This is the same text that appears with the decision on the checklist before downloading the text file.]

Essential 
Y	   states a purpose, problem, objective, or research question
Y	   explains why the problem, objective, or research question is important
...

**Comment by Taher-Ghaleb** [comment]
Hi, is this completely done?

**Comment by eschltz** [comment]
Hi Taher, the code that generates the decision was moved to the top of the checklist this issue is completed.
