### ISSUE TITLE
Hot key for mark all checklist items 'yes'

### ISSUE THREAD

**Issue by drpaulralph** [acmsigsoft/EmpiricalStandards#40]
As a tester
I want to be able to quickly check all the 'yes' radio buttons
So that I can test the checklists faster

We could use a hotkey but I'm open to other solutions. I don't want this to be visible because we don't want to encourage reviewers to just click 'yes to all' without thinking about each criterion.

**Comment by arhamarshad1** [comment]
So far the hotkey solution seems like the only reasonable solution but if don't use a hotkey different browsers have different functionalities for radio buttons if I'm correct. Like in Windows you can use CTRL+Select to select a range of options.

**Comment by drpaulralph** [comment]
Can you explain how exactly to do that?

**Comment by arhamarshad1** [comment]
https://webaim.org/techniques/keyboard/accesskey

**Comment by Taher-Ghaleb** [comment]
What if we add a new parameter to the URL called 'tester' or just 't', for which we program the checklist to show a "yes to all" option? We can make the tester functionality only available through the URL. Here is an example of how it would be used:

We open a checklist:
https://acmsigsoft.github.io/EmpiricalStandards/form_generator/result.html?standard=General+Standard&role=two-phase-reviewer

Then, we append _&tester_ to the end of the URL, like this:
https://acmsigsoft.github.io/EmpiricalStandards/form_generator/result.html?standard=General+Standard&role=two-phase-reviewer&tester

**Comment by drpaulralph** [comment]
Can we could forget about the button and just mark all essential attributes "yes" when &y is appended to the end of the string?

**Comment by Taher-Ghaleb** [comment]
OK, that should work. But, when all "yes" are selected, you want all actions to be automatically executed as well (i.e., the decision will be ACCEPT, the desirable & extraordinary attributes show up, and the download button gets activated)?

**Comment by drpaulralph** [comment]
Yes.

**Comment by Taher-Ghaleb** [comment]
OK, can you test it now, please?

**Comment by drpaulralph** [comment]
Looks good!
