### ISSUE TITLE
Only show desirable and extraordinary attributes possessed

### ISSUE THREAD

**Issue by drpaulralph** [acmsigsoft/EmpiricalStandards#43]
As a reviewer,
when I download my review checklist export, 
I want it to only show the Desirable and Extraordinary attributes that I selected
so that I don't get overwhelmed by all the text. 

If no desirable attributes are selected, the desirable heading should not display. Likewise, if no extraordinary attributes are selected, the extraordinary heading should not display. 

BEFORE:

=================
Review Checklist
=================

Recommended Decision: ACCEPT

Unreasonable Deviations Requiring Revision
F	   presents a clear chain of evidence from observations to findings

Essential
Y	   states a purpose, problem, objective, or research question
...
Y	   defines unit(s) of analysis

Desirable
N	   summarizes and synthesizes a reasonable selection of related work
N	   clearly describes relationship between contribution(s) and related work
N	   states epistemological stance
N	   appropriate statistical power
Y	   reasonable attempts to investigate or mitigate limitations
N	   discusses study’s realism, assumptions and sensitivity of the results to its realism/assumptions
N	   provides plausibly useful interpretations or recommendations for practice, education or research
N	   openly shares data and materials to the extent possible within practical and ethical limits
N	   concise, precise, well-organized and easy-to-read presentation
N	   visualizations advance the paper’s arguments or contribution
Y	   clarifies the roles and responsibilities of the researchers
N	   provides an auto-reflection or assessment of the authors’ own work
N	   uses multiple raters for any subjective judgments
N	   provides supplemental materials such as interview guide(s), coding schemes, coding examples, decision rules, or extended chain-of-evidence tables
N	   triangulates across data sources, informants or researchers
N	   cross-checks interviewee statements
N	   validates results using member checking, dialogical interviewing, feedback from non-participant practitioners or research audits of coding by advisors or other researchers
Y	   reports the type of case study
N	   describes external events and other factors that may have affected the case or site
N	   uses quotations to illustrate findings
N	   EITHER: evaluates an a priori theory

Extraordinary
N	   applies two or more data collection or analysis strategies to the same research question
N	   approaches the same research question(s) from multiple epistemological perspectives
Y	   innovates on research methodology while completing an empirical study
N	   multiple, deep, fully-developed cases with cross-case triangulation
N	   uses multiple judges and analyzes inter-rater reliability
N	   uses direct observation and clearly integrates direct observations into results
N	   published a case study protocol beforehand and made it publicly accessible

=======
Legend
=======
...

AFTER: 

=================
Review Checklist
=================

Recommended Decision: ACCEPT

Unreasonable Deviations Requiring Revision
F	   presents a clear chain of evidence from observations to findings

Essential
Y	   states a purpose, problem, objective, or research question
...
Y	   defines unit(s) of analysis

Desirable
Y	   reasonable attempts to investigate or mitigate limitations
Y	   clarifies the roles and responsibilities of the researchers
Y	   reports the type of case study

Extraordinary
Y	   innovates on research methodology while completing an empirical study

=======
Legend
=======

**Comment by arhamarshad1** [comment]
I've made it so that only selected Desirable or Extraordinary attributes are shown in the text file. @eschltz could you help trace where the attribute headers are being stored in the saveFile() function? Once you find them just remove them so that they don't show up when none of the desirable or extraordinary attributes are selected.

**Comment by eschltz** [comment]
The headers were being added automatically when moving over each list so I moved them to their own variables. They should now only show up when at least one attribute is selected.
