### ISSUE TITLE
Add an ethics supplement for engineering research

### ISSUE THREAD

**Issue by drpaulralph** [acmsigsoft/EmpiricalStandards#5]
The standards need to do a better job addressing research ethics. Please use this issue thread to make suggestions.

**Comment by nicolasgold** [comment]
One might incorporate statements in the Essential section of the General Standard along these lines:
•	discusses the research ethics issues arising in undertaking the work, or if no issues are deemed to have arisen, discusses what issues were considered potentially relevant and why these were dismissed.
•	where formal ethics approval has been obtained, this must be stated including any reference numbers.
 
I included the ‘no issues’ clause to differentiate absence of discussion from determination of there being no ethical issues to consider.  Stating these in the general standard would then provide a basis against which discussion of things like inability to share data owing to ethical limits (referred to elsewhere in the standard) could rest.

**Comment by drpaulralph** [comment]
We now have ethics supplements for research with human participants and research with secondary data. We still need an ethics supplement for engineering research (i.e. research that proposes tools, technologies or other functional artifacts)
