### ISSUE TITLE
Correct weird formatting of indented lists 

### ISSUE THREAD

**Issue by drpaulralph** [acmsigsoft/EmpiricalStandards#50]
Have a look at the screenshots below. Many of the standards have simple lists like this one from the engineering standard, using manual line breaks to make the text easier to understand.

<img width="700" alt="Screen Shot 2021-07-13 at 4 23 47 PM" src="https://user-images.githubusercontent.com/33912489/125512923-931f4d52-179c-4bbd-b6e1-4750ba54f45e.png">

When this attribute appears in the checklist, the manual line breaks are removed:
 
<img width="717" alt="Screen Shot 2021-07-13 at 4 24 07 PM" src="https://user-images.githubusercontent.com/33912489/125512920-3febc816-3bc4-465e-b9fb-41671fd2d40e.png">

We can make changes to the standards themselves, if necessary, to get this to look better. Right now the parser doesn't seem to recognize indented lists like this:
- Item 1
  - Subitem 1
  - Subitem 2
  - Subitem 3
- Item 2
  - ...

**Comment by eschltz** [comment]
It seems this issue was caused by the fix I used to remove the excessive whitespace between certain items. The parser should only remove line breaks from the end of each item now.
