### ISSUE TITLE
Potential improvements to case study standard

### ISSUE THREAD

**Issue by drpaulralph** [acmsigsoft/EmpiricalStandards#6]
The case study standard doesn't say much about theory. Is it desirable for case study to do one or more of the following?
- generate a theory 
- base its coding scheme on a theory, or
- test an a priori theory

**Comment by sbaltes** [comment]
Speaking of theory: What about a supplemental section about Theory vs. Theoretical Framework vs. and Conceptual Framework, similar to [this](https://journals.lww.com/academicmedicine/Fulltext/2020/07000/The_Distinctions_Between_Theory,_Theoretical.21.asp) paper?

**Comment by drpaulralph** [comment]
Added stuff about theories to the case study paper. We're avoiding a framework like @sbaltes suggested (for now) because different people use the same terms inconsistently.
