### ISSUE TITLE
Create a standard for Replication Studies

### ISSUE THREAD

**Issue by david-istvan** [acmsigsoft/EmpiricalStandards#80]
Carver (2010) proposed guidelines for reporting replications. A [2014 special issue in EMSE](https://doi.org/10.1007/s10664-013-9290-8) uses four papers to test the reporting guidelines, and the editorial provides further pointers to the literature about replication studies.

Dennis and Valacich propose a useful taxonomy in their [replication manifesto](https://doi.org/10.17705/1atrr.00001).

[da Silva et al.](https://doi.org/10.1007/s10664-012-9227-7) carry out a systematic mapping study of replication studies in software engineering and draw a number of informative and actionable conclusions.

References:
- Carver JC (2010) Towards reporting guidelines for experimental replications: a proposal. In: RESER’2010: proceedings of the 1st international workshop on replication in empirical software engineering research

**Comment by drpaulralph** [comment]
Prof Carver offered some time ago to draft a standard for replication studies but I guess he never got to it. I recommend reaching out to him directly and offering to help.

**Comment by JeffCarver** [comment]
Please also see this recent [paper](https://dl.acm.org/doi/10.1145/3470652) published in the CS Education literature. The goal was to assess the completeness of papers with regard to their replicability.
