### ISSUE TITLE
Checklist generation for the Replication standard

### ISSUE THREAD

**Issue by david-istvan** [acmsigsoft/EmpiricalStandards#88]
Please, provide checklist generation functionality for https://github.com/acmsigsoft/EmpiricalStandards/blob/master/docs/Replication.md.

**Comment by drpaulralph** [comment]
@david-istvan the replication standard looks ready. Do you want to add a selection for it in the tool generator and see if it works?

**Comment by drpaulralph** [comment]
All done.
